command_timeout = 10000
add_newline = false
scan_timeout = 30

format = """
$directory\
$all\
$git_branch\
$fill\
$git_status\
$git_commit\
$line_break\
$shell\
$character\
"""

[line_break]
disabled = false

[fill]
symbol = " "

[git_branch]
format = "$symbol$branch"
symbol = " "

[git_commit]
commit_hash_length = 4

[git_status]
format = '\[$all_status$ahead_behind\]'
up_to_date = "✓"
staged = '[++\($count\)](green)'

[shell]
fish_indicator = "Fish"
zsh_indicator = "Zsh"
nu_indicator = "Nu"
elvish_indicator = "Edhelen"
style = "dimmed"
disabled = false

[directory]
format = "[$path ]()"
truncation_symbol = "…/"
truncate_to_repo = true
truncation_length = 2
fish_style_pwd_dir_length = 1

[java]
symbol = "💩 "

[username]
show_always = false
disabled = true
